version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker): "
      include: "scope"
    labels:
      - "dependencies"
    reviewers:
      - eser

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(gh-actions): "
      include: "scope"
    labels:
      - "dependencies"
    reviewers:
      - eser
