name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "**"

  # schedule:
  #   - cron: "18 21 * * 6"

jobs:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read # Needed to clone the repository

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        deno-version:
          - 1.38.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Check formatting, linting, license headers, types and run tests
        run: deno task ok

      - name: Generate coverage report
        run: deno task test:coverage-gen

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          name: ${{ matrix.os }}
          files: ./_etc/coverage.lcov
